cc_library(
    name = "dataloader",
    srcs = [],
    linkopts = ["-lm"],  #  Math library
    visibility = ["//visibility:public"],
    deps = [],
)

cc_binary(
    name = "dataloader",
    srcs = ["dataloader.cpp"],
    deps = [],
)
